### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by loganminhdang** [ZJUFanLab/bulk2space#3]
Hey team, thanks for coming up with this useful tool. I'm looking to follow your tutorial on hypothalamus deconvolution, and it seems the lcm.gz data file on your Github only contains a single file, without all the processes count matrices and cell metadata table. Is that supposed to be the case? If so, I wonder how I should process this single file to generate the input data I need. Thanks for any heads up!

**Comment by FowardYang** [comment]
Hi, all the data used in the hypothalamus deconvolution tutorial have been submitted as `lcm.gz` to [](https://github.com/FowardYang/bulk2space_data/blob/master/hypothalamus/lcm.gz), and you can download and unzip it directly.

**Comment by ForwardYang98** [comment]
Hi, all the data used in the hypothalamus deconvolution tutorial have been submitted as `lcm.gz` to [here](https://github.com/FowardYang/bulk2space_data/blob/master/hypothalamus/lcm.gz), and you can download and unzip it directly.

**Comment by loganminhdang** [comment]
I was aware of that directory and previously downloaded the file. However, upon trying to unzip it, I only received one file (which is over 2GB in size), which I presume is an amalgamation of all the data you used (bulk gene expression matrix, single-cell metadata, spatial locations etc.). I'm unsure how to process this file to generate the input data needed to replicate your hypothalamus analysis.

**Comment by ForwardYang98** [comment]
<img width="555" alt="截屏2022-07-04 下午6 22 24" src="https://user-images.githubusercontent.com/75570743/177135612-e026c212-7984-4d1b-a921-5231fac8e827.png">
We have downloaded the data and unzipped it, and the bulk gene expression matrix, single-cell metadata, spatial locations, etc are all here.

**Comment by loganminhdang** [comment]
Maybe it's just the way I unzipped the file. When I view the lmc.gz file in both WinRAR and 7-zip, I only saw one file and not the files shown in your attached photo. Is there a specific manner in which I should unzip the file?

![image](https://user-images.githubusercontent.com/105299246/177164450-93ec4817-4c5d-4aa3-8220-5fe3e610b9f7.png)

**Comment by ForwardYang98** [comment]
Hi, we have tried some ways:

1. Make sure to download the `lcm.gz` only rather than the whole `hypothalamus file`
![WechatIMG83](https://user-images.githubusercontent.com/75570743/177232940-4b36df9f-0e3e-4bd0-8500-89e78fa9cd3d.png)
2. For `macOS`, you can directly unzip it with the default unzip manner or `The Unarchiver`
3. For `windows`, you can add the `.gz` suffix to the file unzipped and unzip again with `WinRAR` or `Bandizip`
4. We also upload the data in `zip` format to [Google Drive](https://drive.google.com/file/d/1ZGstNzVX-YxofrPP8ZVmr0Zu4nd_O_bZ/view?usp=sharing), and you can download it if all the ways above failed.

Hope it would help you.

**Comment by loganminhdang** [comment]
Thanks a lot for your support!
